Samsung/rlottie

example/efl_animview.cpp
efl_animation_view_keyframe_set/get are deprecated.
=> example : Change keyframe_set/get to progress_set/get APIs

inc/rlottie.h, src/lottie/lottieanimation.cpp
=> [rlottie] Added setDrawRegion api to Surface for supporting subsurface rendering

inc/rlottie.h, src/lottie/lottieanimation.cpp, src/lottie/lottiemodel.h, src/lottie/lottieparser.cpp
#8 
usage:
rlottie::Animation player = rlottie::Animation::loadFromFile(filePath);
for (auto &info : player->layers()) {
printf("name: %s , in: %d, out: %d\n", std::get<0>(info).c_str(), std::get<1>(info), std::get<2>(info));
}
=> [rlottie]: Added layers() api to return the layer info list of the composition

src/lottie/lottieitem.cpp, src/vector/vdrawhelper.cpp, src/vector/vdrawhelper.h, src/vector/vpainter.cpp, src/vector/vpainter.h
=> rlottie/vector: support subsurface rendering with arbitrary offset.

src/lottie/lottiemodel.h
start and end vaule were not properly updated in the presence of trim offset value.
=> rlotti/model: Fix issue with trim offset calculation.

.travis.yml
=> rlottie: added travis ci support.

src/vector/config.h, src/vector/vimageloader.cpp
=> rlottie: added compilation switch to build imageloader as part of rlottie library.

example/CMakeLists.txt, example/lottie2gif.cpp
=> added missing cmake file

example/demo.cpp, inc/rlottie.h, src/lottie/lottieanimation.cpp, src/lottie/lottieitem.cpp, src/lottie/lottieitem.h, src/lottie/lottieproxymodel.h
now user can pass a lambda expression to setValue() api for changing dynamic property.
=> rlottie: added support of lambda expression in setValue.

src/lottie/lottieparser.cpp
With older bodymovin pluggins the interpolator cache string sometimes
dosen't match with the in and out tangent results into wrong animation.
So parse the interpolator string whenever available.
=> lottie/parser: Fixed regression of interpolator string handling.

src/vector/vmatrix.cpp
This reverts commit e1cf42ba8c1628f6c06cbb6acb78b0ac81521c8f.
The fall through code is as per design.
=> Revert "vector: fix a compile error of strict fallthrough case check."

src/lottie/lottieitem.cpp, src/lottie/lottieparser.cpp
- added checking for hidden layers
- fixed layer.visible() if layer is hidden
=> - hidden layers fix

example/lottie2gif.cpp
commit from vtorri https://github.com/Samsung/rlottie/pull/176/commits/af65ac2c6a6e819573788c9d5df74067ee819b73
=> rlottie/example: Make lottie2gif work in windows

src/vector/vrect.h
=> vector: Fix regression in VRecF for uniform initialization constructor

src/vector/vraster.cpp
With some data it is possible to get a `short` overflow in `SW_FT_Outline` members, this leads to undefined behaviour on attempt to render that outline.
I'm not sure if we need to check the return value of `outRef.grow(points, contors);` in that case where we get `points` and `contors` from `SW_FT_Stroker_GetCounts`, maybe they're always good there.
=> Fix possible SW_FT_Outline points overflow.

inc/rlottiecommon.h, src/lottie/lottieitem.cpp, src/lottie/lottiemodel.h, src/lottie/lottieparser.cpp, src/lottie/lottieproxymodel.h, src/vector/vdrawable.cpp, src/vector/vdrawable.h, src/vector/vraster.cpp, src/vector/vraster.h
=> rlottie: Fix typo

src/lottie/lottiemodel.h, src/lottie/lottieparser.cpp
this patch checkes if the layer has assigned itself as parent.
=> lottie/parser: check for layer data integrity

src/lottie/lottieparser.cpp
Checks for possibly invalid data.
=> Check that root layer was found.

src/lottie/lottieparser.cpp
Asserts could be disabled in the Release build.
=> Fix possible out of bounds reading.

README.md
Updated content for the dynamic property.
I referenced the documentation of lottie android and modified it to suit rlottie.
=> README.md : Add dynamic property

example/demo.cpp
Change json sample and add more cases.
=> Example : Enhancement dynamic property demo

inc/rlottie_capi.h, inc/rlottiecommon.h, src/binding/c/lottieanimation_capi.cpp
Add lottie_animation_get_markerlist() api
User can use this api and get information about each marker.
=> CAPI: Support Marker feature for CAPI.

example/lottieview.cpp, example/lottieview.h
Change findFrameAtMarker return type.
=> Example: Change findFrameAtMarker return type.

example/lottieview.cpp, example/lottieview.h, example/lottieviewtest.cpp
The existing Strategy::eflVg make a vector object treeusing a node tree
from C++ rlottie API. But it didn't work well.
Loading a vector file into evas_object_vg works the same as internally.
[Test]
Prepare for latest EFL
rlottie build
./build/example/lottieviewTest 4
=> Example : Update Strategy::eflVg in lottieview

src/lottie/lottieparser.cpp
Caused by recent refactoring of the model objects.
=> rlottie: Fix build break for debug build.

example/meson.build
The class name will be updated.
efl_ui_animation_view -> efl_ui_vg_animation
So add referenced file path.
=> example : Add reference header file for updated class name

example/demo.cpp, src/binding/c/lottieanimation_capi.cpp, src/lottie/lottieitem.cpp, src/lottie/lottieitem.h, src/lottie/lottieproxymodel.h
Use setValue\<rlottie::Property::TrPosition\> and return rlottie::Point type.
Example) example/demo
=> rlottie: Supports the Transform Position property.

src/lottie/lottieitem.cpp, src/lottie/lottieitem.h, src/lottie/lottieproxymodel.h
mData is same as mModel in LOTContentGroupItem. So remove mData member.
=> lottie: Remove duplicate model data.

example/demo.cpp, src/lottie/lottieitem.cpp, src/lottie/lottieproxymodel.h
Move value calculation given by property to proxy model
And add more sample to the demo.
=> rlottie: Refactor transformation matrix of proxymodel

src/lottie/lottieitem.cpp, src/lottie/lottieitem.h
During rendering layers with mask/matte we need intermediate buffers
by keeping the surface cache we can reuse the same buffer for different
layer rendering to reduce memory footprint.
=> optimization: added SurfaceCache to reduce intermediate buffers.

src/lottie/lottiemodel.h, src/lottie/lottieparser.cpp
For now, it does not parse whole text properties including text animators.
=> lottie/parser: parse text properties

src/vector/text/meson.build, src/vector/text/vtextshaper.cpp, src/vector/text/vtextshaper.h
=> text: add VTextShaper class

src/binding/c/lottieanimation_capi.cpp
as va_arg() is a macro it affects the function size . this reduces the function size by .5KB.
=> lottie: refactor lottie_animation_property_override implementation.

.travis.yml, meson.build, src/lottie/lottieitem.cpp, src/meson.build, src/vector/vglobal.h, src/vector/vrle.cpp
updated travis to check this setup.
=> meson: Fix build issue when thread support is disabled.

src/vector/CMakeLists.txt, src/vector/meson.build, src/vector/vdrawhelper.cpp, src/vector/vdrawhelper.h, src/vector/vdrawhelper_common.cpp, src/vector/vdrawhelper_neon.cpp, src/vector/vdrawhelper_sse2.cpp, src/vector/vglobal.h, src/vector/vpainter.cpp
- replaced implementation form qt.
- refactor render function table.
- ran clang-format
=> vector: rendering refactor.

src/lottie/lottiemodel.h, src/lottie/lottieparser.cpp
As only Property<VPointF> in Transform object has the tangent info
added a tag in Property to differentiate form other property.
This will add tangent info to only property that require them.
=> optimization: refactor Property class for size optimization.

src/vector/vbezier.cpp, src/vector/vline.h
- force VLine::length() function to be inline.
=> optimization: optimize VBezier::length()

src/lottie/lottieitem.cpp, src/vector/vrle.cpp, src/vector/vrle.h
=> vector/vrle: added free function for + and & operator

.gitignore
=> ignore DS_Store

.gitignore
- Add the text 'builddir_wasm' in .gitignore
There is folder that should not be uploaded.
=> Modify: Update .gitignore

src/wasm/rlottiewasm.cpp
Added following functions for lottie animation
- setFillColor
- setStrokeColor
- setOpacity
- setFillOpacity
- setStrokeOpacity
- setStrokeWidth
- setPosition
- setRotation
- setAnchor
- setScale
=> Add extra functions for lottie animation to use them in rlottie viewer

example/win32Player/rlottiePlayer.vcxproj, vs2019/rlottie.vcxproj
Add project configuration for release build
+ add ignore warning 4996
=> vs2019: Add release build option

src/vector/vpath.cpp
If width or heigth is 0 rlottie returned for drawing rect.
But it makes sense to draw line even if width or height is 0.
=> rlottie: draw line if width or height is 0

src/lottie/lottieitem.cpp, src/lottie/lottieitem.h, src/lottie/lottiemodel.h, src/lottie/lottieparser.cpp
- Currently RoundedCorner object only affects Rect object round property.
- yet to implement for Shape object.
=> Added support for RoundedCornor objects.

CMakeLists.txt, example/CMakeLists.txt, src/vector/stb/CMakeLists.txt
MSVC can't recognize these parameters.
=> CMake: fix MSVC warnings

src/lottie/lottiemodel.h
Also remove unnecessarily check of mExtra->mAsset in the asset() getter.
=> Fix dereferencing of null pointer in model::Layer::solidColor() getter

format, src/lottie/lottiefiltermodel.h, src/lottie/lottieitem.cpp, src/lottie/lottieitem.h, src/lottie/lottieitem_capi.cpp, src/lottie/lottiekeypath.cpp, src/lottie/lottiekeypath.h, src/lottie/lottiemodel.h, src/vector/vbitmap.cpp, src/vector/vbitmap.h, src/vector/vbrush.cpp, src/vector/vbrush.h, src/vector/vdrawable.cpp, src/vector/vdrawhelper.cpp, src/vector/vdrawhelper.h, src/vector/vdrawhelper_common.cpp, src/vector/vglobal.h, src/vector/vpainter.cpp, src/vector/vpath.h, src/vector/vraster.cpp, src/vector/vrle.cpp, src/vector/vrle.h
-- added format script to run clang format on latest commit.
=> replace uint ushort and uchar typedefs with uint32 uint16 and uint8

src/lottie/lottieparser.cpp, src/vector/vdrawhelper.cpp
=> Fix two crashes on fuzzed JSONs

src/lottie/lottieitem.cpp
use parent alpha in the Fill::updateContent method to calculate combined alpha.
=> lottieitem: Added alpha in Fill::updateContent method.

src/lottie/lottieitem.cpp, src/lottie/lottieitem_capi.cpp
Pass combinedAlpha when not complexContent.
=> Pass combinedAlpha when not complexContent.

src/lottie/lottieitem.cpp, src/lottie/lottiemodel.cpp, src/lottie/lottiemodel.h, src/vector/freetype/v_ft_raster.cpp
Add validation checks to address potential vulnerabilities in case of a malicious Lottie file
Adds:
- Type check for CompLayer() before casting to model::Layer
- Bounds checking for Gradient::populate()
- Frames vector empty check
- Rejection of outliers
=> Fix security vulnerabilities in Lottie file handling
