Samsung/rlottie

CMakeLists.txt
rlottie.pc.in

make -stdc++14 dependency private so that its not a requirement to link against rlottie library

rlottie: remove dependancy of -stdc++14 flag to link against rlottie library

---

example/lottieview.cpp
example/lottieview.h
inc/rlottie.h
inc/rlottie_capi.h
src/binding/c/lottieanimation_capi.cpp
src/lottie/lottieanimation.cpp
src/lottie/lottieloader.cpp
src/lottie/lottieloader.h
src/lottie/lottieparser.h

rlottie: now loadFromData() api takes resourcePath for loading external resource

---

src/vector/vpainter.cpp

[rlottie]: clear any existing brush data before drawing bitmap.

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h

#12 
Update the drawable node by using both gradient alpha as well as parent alpha.

rlottie: Use opacity value when rendering gradient.

---

src/lottie/lottieitem.cpp
src/lottie/lottiemodel.cpp
src/lottie/lottiemodel.h
src/vector/freetype/v_ft_math.cpp
src/vector/vglobal.h
src/vector/vimageloader.cpp
src/vector/vpainter.cpp
src/vector/vpath.cpp
src/vector/vrect.cpp

1、__builtin_clz support
2、 V_UNUSED  and V_REQUIRED  support
3、dlopen dlclose support
4、some c++/c header no found  solve
5、vCompare has two define ,one of arg is double type,and one is float type.  If your write `vCompare(mDashOffset, 0)` may be errror on same compiler（such as msvc）。so I change same of this code  to `vCompare(mDashOffset, 0.0f)`
Introduce an interesting resource to your:
https://skottie.skia.org
at last sorry for my english。If you know Chinese, let's communicate in Chinese。

Win support

---

src/lottie/lottieitem.cpp

When do an Intersect mask, it need to initialize rle like a Subtract.

rlottie: Fix issue with intersect mask

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h
src/lottie/lottiemodel.cpp
src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp

Below issues are fixed
1. when repeater has 0 copies.
2. when "copies" property has animation.
3. Wrong matrix computation when repeater transformation has anchor value.
Fixed abstract_circle.json resource.

rlottie: Fix issue with repeater object.

---

inc/rlottie.h
src/lottie/lottieanimation.cpp

c++11 only supports static constexpr function with one return statement.
so our maptype() function is valid in c++14 but not on c++11.
to work around used the explicit class instantiation to map property type to value type.

rlottie/header: fixed issue with public header dependency of c++14

---

src/lottie/lottieitem.cpp

Mask item in AE has its own maskOpacity property. As mask items are local to layer and it affects all the visualization of that particular layer , inherited opacity should only affect the content of the layer not the mask of the layer.

rlottie: mask item shouldn't inherit parent opacity

---

src/lottie/lottiemodel.h

When lottie file is static but has more than 1 frame of static data
we should return the duration() value correctly.

rlottie: Fixed wrong calculation of duration.

---

src/lottie/lottieitem.cpp
src/lottie/lottiemodel.h

Precomp layers can be static with more than 1 frame inside it.
so always propagate update to all its child layers.

rlottie: always propagate update for precomp layer.

---

src/lottie/lottieparser.cpp

Take only the 1st element and discard the rest.

rlottie/parser: Fix float data parsing when data in array form.

---

src/lottie/lottiemodel.h

In AE start and end value can naver be -ve. but the final
start and end value after applting interpolator curve could be -ve.
So refactor to always take the -ve value into account.

rlottie/trim: Fix trim segment calculation.

---

inc/rlottiecommon.h
src/lottie/lottieitem.cpp
src/vector/vmatrix.h

The image properties are image data, size, and matrix information.
If the lottie item is an image item, the image property is stored in the Nodelist.

lottieitem: Add image property in LOTNode

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h

When the precomp layer has alpha transparency and has more than 1 child layer and they overlap each other
if we just propagate the alpha to child layer it will be applied twice in overlapped area.
in this case we treat the precomp layer as complex content and don't propagate the alpha transparency.
instead we create a buffer and draw all the child layers and then we blend with the main buffer
with the alpha transparency value.

rlottie: Fix precomp layer rendering issue when it has alpha value

---

inc/rlottiecommon.h
src/lottie/lottieitem.cpp

When a layer has transparency, we need to send it to layer node.
So I add mAlpha member to the LOTLayerItem.

lottieitem : Fix layer alpha transparency issue.

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h

The offscreen buffer is created on demand if the layer has any matte.
so we only create the buffer once and reuse for subsequent frame rendering.

rlottie: Keep an offscreen buffer in the layer.

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h
src/vector/vdrawable.cpp
src/vector/vdrawable.h
src/vector/vraster.cpp
src/vector/vraster.h

Moved the Rle Generation to Rasterizer class which will take care of
handling async rle generation efficiently by reusing Task.
Now Rle Task scheduler will take a shared_ptr to the Task data which will
be created once in Rasterizer.

rlottie: Refactor Rle Generation to optimize memory allocation.

---

src/vector/vimageloader.cpp

Indeed, when cross-compiling on Linux, which has a case
sensitive file system, and as minwg-w64 provides windows.h,
we must use lower case name for header files.

Iamage loader: include windows.h and not Windows.h

---

example/lottie2gif.cpp
src/lottie/lottieloader.cpp

Fix also basename() implementation by using strrchr() and not strchr()

fix dirname() implementation of Windows in lottieloader.cpp

---

src/lottie/lottieloader.cpp
src/lottie/lottieparser.cpp

- when resource dosen't have valid header
- layer dosen't have a transform object

rlottie: Fix Crash when the resource is not a valid lottie resource

---

src/lottie/lottieitem.cpp
src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp

- better packing
- move seldom use data to extra storage
- reuse layerSize for layer as well as solidlayer size.
Now Size(LOTLayerData) reduced from 262 to 128 byte.

lottie/optimize: Reduce LOTLayerData  size

---

meson.build

cmake config files needed by cmake's find_package to able to find rlottie.

meson: generate cmake config files

---

src/meson.build
src/vector/stb/meson.build

As all the meson variables are in global scope the compiler_flags
in stb module reseted all the optimization flag set in the src directory
which increased the library size by 100KB.

meson: Fix regression in library size

---

CMakeLists.txt

Do not override the value of the -O compiler flag. Instead use the MinSizeRel as default. This allows a user to redefine build profile including optimization level via command line interface.

Do not override optimization level

---

CMakeLists.txt
src/vector/stb/CMakeLists.txt

Also fix several little issues:
* Do not define the LOT_BUILD global macro. Use instead the DEFINE_SYMBOL target property.
* Add the `-fvisibility=hidden` compiler flag for the image loader. It seems to be forgotten by mistake.

Configure CMake to allow build static rlottie lib

---

src/vector/vcompositionfunctions.cpp
src/vector/vdrawhelper.cpp
src/vector/vdrawhelper_neon.cpp
src/vector/vdrawhelper_sse2.cpp

This allows linking rlottie statically with statically linked Qt library that has the same global methods defined.

Fix linking with static Qt.

---

src/lottie/lottieparser.cpp

If the data is corrupt we get `nullptr` value in `str` variable.

Fix crash in a bad file reading.

---

src/vector/vdasher.cpp

this was only comparing the 1st dashinfo because of missing array subscript operator.

vdasher: fixed regression from last commit

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h
src/lottie/lottiemodel.cpp
src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp
src/lottie/lottieproxymodel.h
src/vector/vdasher.cpp
src/vector/vdrawable.cpp
src/vector/vdrawable.h

- reduce Stroke and GStroke model object size by keeping a vector instead of fixed array property.
- keep a vector instead of fixed size array in model.
- keep a vector instead of fix size array in shadow tree.
- refactor getDashInfo() to DashProperty class and reuse by both Stroke and GradientStroke model object.
- enable move constructor in LOTAnimatable class to support creation vector of objects.

vdasher: refactor dash property parsing and handling.

---

inc/rlottie_capi.h
src/binding/c/lottieanimation_capi.cpp

This function needs keypath and type of string type.
And needs values as variable arguments.
The usage of this function is written in docs.

CAPI: Add capi to support the dynamic properties

---

src/lottie/lottieparser.cpp

I'm not sure how this should be handled correctly, but in case of some invalid data currently it crashes with a null pointer dereference.

Fix crash on invalid data.

---

src/vector/vsharedptr.h

why?
std::shared_ptr uses 2 pointer instead of 1.
we don't always need atomic ref count thats why rc_ptr
in situation where atomic ref cound needed use arc_ptr

vector: added support rc_ptr and arc_ptr to vector

---

src/lottie/lottiemodel.cpp
src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp

In a complex lottie resource layer counts can exceed above 100 or in
some cases 1000. As in each frame rendering we visit the whole tree
allocating all of them using a local allocator will speed up the tree
visit as well as creation and destruction.
As the number of layer objects are fixed in a resource we can make use of
a dumb monotonic allocator to allocate all objects in one place.

lottie/model: keep a stat of model for future local allocator.

---

src/lottie/lottieparser.cpp

In case of invalid data this may lead to writing out of bounds on the stack.

Fix possible stack corruption.

---

CMakeLists.txt
rlottie.expmap
src/lottie/lottieanimation.cpp
src/meson.build

This prevents internal libstdc++ things from being visible outside the rlottie library. Look at all available symbols using the following command.
nm --demangle --defined-only --dynamic librlottie.so
Also the commit puts configureModelCacheSize into the rlottie namespace that fixes a linker error against this function.

Introduce export map to completely hide private symbols

---

src/vector/freetype/v_ft_math.cpp

vtune profile shows branch miss in ft_trig_pseudo_polarize and ft_trig_pseudo_rotate
as both the if cases does similar expensive computation move then to start so that
we will not pay high penalty during branch miss.

vector/ft: refactor to reduce branch miss.

---

src/vector/vraster.cpp

check if the previous task is finished before reseting the task .
if the previous task is not finished may lead to inconsistant task state.

vector/rasterizer: safe rletask reset.

---

src/lottie/lottieanimation.cpp
src/vector/vraster.cpp

when the queue is empty the thread tries to steal from other queue
and it was doing it 32 times .. changed it to 2 as it was spinning for
long time before going to  sleep. As we always give the tasks in batches
we can reduce the spin time.

rlottie: reduce polling count for task scheduler to 2.

---

src/vector/vdrawable.h

Fix to not showing animation in CAPI side.

VDrawable: Fix initial value of an enum

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h
src/vector/CMakeLists.txt
src/vector/meson.build
src/vector/varenaalloc.cpp
src/vector/varenaalloc.h

This flattens the shadow tree memory layout for cache efficiency as well as moved the object life cycle management to the allocator . The allocator will clean up all the objects created by it when it goes out of scope. This patch improves the benchmark performance by 5%.

Create Shadow tree using a Local Arena allocator.

---

src/lottie/lottieitem.cpp

If the drawable is not updated in case of ZERO opacity it will keep the old value and
will render the old content.

rlottie: update the drawable before returning the result.

---

inc/rlottiecommon.h
src/lottie/lottieitem.cpp
src/lottie/lottieitem_capi.cpp
src/vector/vdrawable.cpp
src/vector/vdrawable.h

We need to expose the ketpath corresponding to the 'Fill' and 'Stroke' content.
The drawable receives the name and passes it to the node of capi.

Expose name info of drawable node

---

src/vector/vdrawable.cpp
src/vector/vdrawable.h

The name information passed in is allocated and managed by the parser.
There is no need to duplicate the same data.

vdrawable: Don't strdup for name data

---

src/lottie/lottiemodel.h

Without this fix frameAtPos doesn't return last frame
for position (1 - eps)

Use round in frameAtPos

---

inc/rlottie.h
src/lottie/lottieanimation.cpp
src/lottie/lottieloader.cpp
src/lottie/lottieloader.h
src/lottie/lottieparser.cpp
src/lottie/lottieparser.h

Some usecase needs to apply the color filter during parsing for theme
support.
Ex: Same resource can be used for different theme with different colorfilter
which will update the color pallet according to the theme.

rlottie/api: Added loadFromData() api with ColorFilter support

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h
src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp

The following animatable properties are being supported.
- Opacity
- Rotation
- Tracking
- Position
- Scale
- Anchor
- FillColor
- StrokeColor
- StrokeWidth
The following things are not being supported for now.
- Range Selector
- Text Multiline support
- Baseline Shift
- etc

text/item: Apply text's animatable properties

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h
src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp

Just keep one VPath for embedded character's path data instead of list of VPath.
It also renames some functions and classes in text/item.

text/model: small optimization patch for model and item

---

src/lottie/lottieitem.h
src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp

The Unicode class is added. It helps to handle unicode text.

text/model: use unicode for text, chars instead of utf8

---

src/lottie/lottiemodel.h
src/vector/vbezier.cpp
src/vector/vbezier.h

When length of the bezier is known , then pass it to tAtLength function
to avoid doing expensive length() operation again.

perf: added tAtLength(len, totalLength) api to Bezier.

---

CMakeLists.txt

Trying to build rlottie static in Microsoft Visual Studio 2019.
To do so `LOT_BUILD` must be undefined expliciltly in cmake call like ` -DCMAKE_CXX_FLAGS='-DLOT_BUILD=0'`
Added it to CMake file for simplicity, so only ` -DBUILD_SHARED_LIBS=OFF` will be enough.
Also moved some compiler parameters under `NOT WIN32` because MSVC can't recognize them and stops the compilation

Fix MSVC 2019 static build

---

src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp

For some keyframes the cache function was not getting called.
so move the cache logic to outer function and call it when the property
is fully parsed.

parser: Fix the keyframe cache logic.

---

src/vector/stb/meson.build

see https://mesonbuild.com/Reference-manual.html#shared_module

build: use shared_module instead of shared_library

---

src/vector/vrle.cpp

Fixed build with GCC 11 by adding missing `limits` header.

Fixed build with GCC 11

---

CMakeLists.txt

When rlottie is added as a subdirectory in a not Apple and not Windows OS the build fails because it searches rlottie.expmap in the main project source directory
This fixes the problem

Fix CMake build in subdirectory

---

inc/rlottie_capi.h

I'm writing a wrapper library around rlottie and rust-bindgen won't accept local includes with angle braces, only quotes. Not a C/C++ programmer, so I hope this doesn't break anything and is an acceptable change.

#include "fix" for rust-bindgen

---

CMakeLists.txt

These link options make no sense on MSVC and results in warnings. This change removes the warning.
Generally I believe it is ill-advised to add public warnings to a library, instead the client project should be able to control their own warnings.

Remove link warnings on MSVC

---

CMakeLists.txt

Set correct Visual Studio settings [(link)](https://docs.microsoft.com/ru-ru/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019) for static build

/MT and /MTd for MSVC static build

---

src/vector/stb/stb_image.h

On windows, stbi__fopen opens a path containing non-English characters or symbols will fail due to encoding problems, so the filename parameter is assumed to be utf-8 and converted to utf-16, and then call _wfopen_s or _wfopen
This patch will affect function lottie_animation_from_data

patch for handling non-utf8 file path.

---

CMakeLists.txt

When rlottie is being used as a submodule and included with
```
add_subdirectory(rlottie)
target_link_libraries(example rlottie::rlottie)
```
this ensures the include path is correctly passed along.
The `BUILD_INTERFACE` generator leads to this being only available at build-time but not via the exported config that gets installed.

add the /inc folder as an include path at build time

---

src/lottie/lottiemodel.cpp

An attempt to fix [CVE-2021-31317][1], not tested yet.
[1]: https://www.shielder.it/advisories/telegram-rlottie-vdasher-vdasher-type-confusion/

Skip dash array of size one or zero

---

src/lottie/lottieparser.cpp

Avoid calling the abort() function on invalid input data.

Fortify lottie parser

---

src/lottie/lottieitem_capi.cpp

mPath is std::vector array of VPointF as a VPath type.
Since the list of points is passed to the capi structure as a float*,
the size of the capi point list is twice the length of the vector array.
issue :https://github.com/Samsung/rlottie/issues/489

rlottie/capi: Add missing multiply for Path

---

src/lottie/lottiemodel.cpp
src/lottie/lottiemodel.h

Basically, Graeidnt stop's color and opacity are provided as separate arrays.
Stop position and opacity position do not match each other.
Existing code is a sequential approach. It caused problems in various cases of positions.
The improved logic repeats the loop, but no exceptions are raised. It's not complicated, it's simple.
This code referenced the lottie-android library.
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/parser/GradientColorParser.java
test file
[test5.zip](https://github.com/Samsung/rlottie/files/7681472/test5.zip)
before
after

lottiemodel: Improve opacity calculation for gradient stop

---

src/vector/vglobal.h

In some compiation platforms, uint32_t is not equivalent to unsigned int, resulting in compilation errors of overload ambiguous.

replace unsigned int with uint32_t in Int()

---

inc/rlottie_capi.h
src/binding/c/lottieanimation_capi.cpp
src/lottie/lottieanimation.cpp
src/vector/vraster.cpp

To support dynamic loading and unloading of rlottie library safely
we need to deallocate the resource cache as well as safely shutdown all the
worker threads.
current patch only stops the Render and Rle task schedulers when lottie_shutdown is called.
Things yet to be implemented during shutdown phase
- Unload image loader if loaded dynamically.
- Check if we can release some cache resources.
- Currently multiple load and unload of rlottie library will not work as we are not starting the
scheduler again when lottie_init() called multiple time in the same process.

Add lottie_init() and lottie_shutdown() c api.

---

inc/rlottie_capi.h
src/binding/c/lottieanimation_capi.cpp

When rlottie_capi.h is included in other C programs, a compilation error occurs. The error is  function declaration isn’t a prototype, so i create a PR to solve it.

add formal parameter void to lottie_init() and lottie_shutdown()

---

src/lottie/lottieitem.cpp
src/lottie/lottiemodel.h
src/lottie/lottieparser.cpp

As mStartFrame and mEndFrame was counted from 0 and totalFrame() was
calculated as a difference, there were always one frame missing and
the animation rescaled. This patch adds one to the total frames count.
As there is 0.01 subtracted (copied from android implementation, needed
for some resources where frame no is non-whole number), added +2, not +1.
It fixes the problem for all tested resources- requested and all in example/resource.
issue: #527

Fix one frame missing

---

example/lottieview.cpp
example/lottieviewer.cpp

There is a problem (issue #527) with totalFrame() in rlottie.
As lottieviewer didn't showed the actual frame number, but calculated it from
progress, it camouflaged the problem. Now the actual frame number and the
total number of frames are displayed.

example: lottieviewer - fixed frame no

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h

This commit modifies the LottieItem rendering process to match Adobe After Effects blending style. Initially, the entire content of the layer is rendered to an intermediate buffer. Then, the buffer is rendered with applied alpha layer.
Current blending style:
New Blending style:

Update color blending style in LottieItem

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h

Revert "lottieitem: Added alpha in Fill::updateContent method."
This reverts commit fb12ddc8d0195672aa1ade6e181c8b26378ad10d.
Revert "Update color blending style in LottieItem"
This reverts commit 8cb666211b859267ec530ff8798c08c29aefecaf.
Change-Id: I27d3213b04514f6c60eb817aa924ca74103c5b09

offscreen rendering of shape layer

---

src/lottie/lottieitem.cpp
src/lottie/lottieitem.h

In following cases,
```c++
animation->setValue<Property::FillColor>("**", red);
animation->render(0, surface);
// after render is finished
animation->setValue<Property::FillColor>("**", blue);
animation->render(0, surface);
```
Or
```c++
animation->setValue<Property::FillColor>("**", [&](const FrameInfo& info) {
return colors->getColor();
});
colors->setColor(red);
animation->render(0, surface);
// after render is finished
colors->setColor(blue);
animation->render(0, surface);
```
the second render request for both cases should not be ignored even if it's the same request as previous.

Do not skip update when it has dynamic property
